spring.application.name=mes-service


server.port=8081

#DB config
spring.datasource.url=jdbc:mysql://localhost:3308/dev
spring.datasource.username=sovon9
spring.datasource.password=password

spring.jpa.show-sql=true

# eureka
spring.cloud.discovery.enabled=false

#config-service
spring.config.import=optional:configserver:http://localhost:8763
spring.cloud.config.username=configUser
spring.cloud.config.password=password
spring.cloud.config.name=${spring.application.name}
spring.cloud.config.label=1.0.0

#retry-config
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.initial-interval=1000

#graphql config
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql
spring.graphql.schema.introspection.enabled=true

spring.main.allow-bean-definition-overriding=true